
services: 
  api: 
    build: ./api
    container_name: dockerapp
    ports: 
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
    
  client:
    build: ./client
    container_name: react_c
    ports:
      - "80:80"  # This port mapping is just for local testing if needed
    depends_on:
      - api
    
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_server
    ports:
      - '5000:80'
    depends_on:
      - client
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx configuration
    
